name: Build and Deploy Jekyll Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install ruby-full build-essential zlib1g-dev
          gem install jekyll bundler
          bundle install
      - name: Build Jekyll Site
        run: JEKYLL_ENV=production bundle exec jekyll build
      - name: Copy to remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: _site/
          target: /beta.buendnerclub.ch
