name: Build and Deploy Jekyll Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: '3.2.2'
      - name: Install deps
        run: |
          gem install jekyll
          bundle install
      - name: Build Jekyll Site
        run: JEKYLL_ENV=production bundle exec jekyll build
      - name: Copy to remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: '_site/*'
          target: /beta.buendnerclub.ch/
          strip_components: 1
          rm: true
